### PR TITLE
(SIMP-1899) Create ssh_authorized_key resources

### PR DESCRIPTION
**Pull request by jeefberkey**
SIMP-1899 #comment added generator for ssh_authorized_key

### CODE REVIEW

**Comment by jeefberkey** [comment]
https://gitlab.com/simp/pupmod-simp-ssh/pipelines/36762011

**Comment by trevor-vaughan** [comment]
@jeefberkey PR looks good but would you mind adding a BIG warning somewhere in here that using this on large numbers of users is about the worst idea ever and you'll probably tank your puppet server?

**Comment by trevor-vaughan** [comment]
@jeefberkey Yeah, I know but we've found that we have to plop that warning on everything that might do this type of thing since it's patently not a puppet warning.

**Comment by nick-markowski** [comment]
Formatting looks good, visual +1

**Pull request merged**
