### PR TITLE
Add some ssh::server::conf params 

### PR DESCRIPTION
**Pull request by pillarsdotnet**
Add the following `ssh::server::conf` params:

- AllowGroups
- AllowUsers
- DenyGroups
- DenyUsers
- LoginGraceTime
- LogLevel
- MaxAuthTries

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
@pillarsdotnet Thanks for the patch!

Would you mind reverting the order of the parameters though? I realize that it's not intuitive, but the ones at the top are internal SSH parameters and the ones at the bottom are SIMP-specific items that are generally disabled by default.

If you want to add comments to that affect, that would be great, if not, I can do it prior to adding the PR.

We initially removed all of the items that weren't really useful for day to day activities but I think that you've hit on the right solution of setting them to `undef` so that people can choose to use them if they like.

**Comment by pillarsdotnet** [comment]
Moved the simp-specific options to the bottom.

Pity that `$loglevel` is a reserved metaparameter; worked-around by renaming the param `$ssh_loglevel` and alphabetizing as if it didn't have the prefix.

When I get a chance, I'll add the rest of the missing params; I needed these particular ones for CIS compliance.

**Comment by trevor-vaughan** [comment]
:hourglass_flowing_sand: https://gitlab.com/simp/pupmod-simp-ssh/pipelines/56345239

**Comment by trevor-vaughan** [comment]
@pillarsdotnet This closes the following CIS-related tickets in our JIRA:

* [SIMP-6262](https://simp-project.atlassian.net/browse/SIMP-6262)
* [SIMP-6264](https://simp-project.atlassian.net/browse/SIMP-6264)
* [SIMP-6266](https://simp-project.atlassian.net/browse/SIMP-6266)
* [SIMP-6267](https://simp-project.atlassian.net/browse/SIMP-6267)

For the rest of the SSH items, since it can vary based on the OS, we were thinking about allowing users to just specify an arbitrary, unvalidated, options Hash and simply generating the resources from that. We don't generally like to do this but, in this case, it's very difficult to keep up with every version in every OS as the SSH daemon versions get updated.

The ticket for that is [SIMP-6305](https://simp-project.atlassian.net/browse/SIMP-6305). If you decide to take a stab at it, please let us know (or just assign yourself the ticket in JIRA) so that nobody ends up doing the same work.

**Comment by pillarsdotnet** [comment]
Well, don't merge just yet.  I managed to lock myself out of my Puppet server because the `$macs` option was unacceptable.  There needs to be a step that validates the new config before applying it.

```
Error: /Service[sshd]: Failed to call refresh: Systemd restart for sshd failed!
journalctl log for sshd:
-- Logs begin at Wed 2019-04-03 15:03:21 EDT, end at Thu 2019-04-11 10:20:31 EDT. --
Apr 11 10:20:31 cusppupent01 systemd[1]: Stopping OpenSSH server daemon...
Apr 11 10:20:31 cusppupent01 sshd[6389]: Received signal 15; terminating.
Apr 11 10:20:31 cusppupent01 systemd[1]: Stopped OpenSSH server daemon.
Apr 11 10:20:31 cusppupent01 systemd[1]: Starting OpenSSH server daemon...
Apr 11 10:20:31 cusppupent01 sshd[29237]: /etc/ssh/sshd_config line 159: Bad SSH2 mac spec 'hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com,curve25519-sha256@libssh.org,diffie-hellman-g
roup-exchange-sha256'.
Apr 11 10:20:31 cusppupent01 systemd[1]: sshd.service: main process exited, code=exited, status=255/n/a
Apr 11 10:20:31 cusppupent01 systemd[1]: Failed to start OpenSSH server daemon.
Apr 11 10:20:31 cusppupent01 systemd[1]: Unit sshd.service entered failed state.
Apr 11 10:20:31 cusppupent01 systemd[1]: sshd.service failed.

Error: /Service[sshd]: Systemd restart for sshd failed!
journalctl log for sshd:
-- Logs begin at Wed 2019-04-03 15:03:21 EDT, end at Thu 2019-04-11 10:20:31 EDT. --
Apr 11 10:20:31 cusppupent01 systemd[1]: Stopping OpenSSH server daemon...
Apr 11 10:20:31 cusppupent01 sshd[6389]: Received signal 15; terminating.
Apr 11 10:20:31 cusppupent01 systemd[1]: Stopped OpenSSH server daemon.
Apr 11 10:20:31 cusppupent01 systemd[1]: Starting OpenSSH server daemon...
Apr 11 10:20:31 cusppupent01 sshd[29237]: /etc/ssh/sshd_config line 159: Bad SSH2 mac spec 'hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com,curve25519-sha256@libssh.org,diffie-hellman-g
roup-exchange-sha256'.
Apr 11 10:20:31 cusppupent01 systemd[1]: sshd.service: main process exited, code=exited, status=255/n/a
Apr 11 10:20:31 cusppupent01 systemd[1]: Failed to start OpenSSH server daemon.
Apr 11 10:20:31 cusppupent01 systemd[1]: Unit sshd.service entered failed state.
Apr 11 10:20:31 cusppupent01 systemd[1]: sshd.service failed.
```

**Comment by pillarsdotnet** [comment]
> For the rest of the SSH items, since it can vary based on the OS, we were thinking about allowing users to just specify an arbitrary, unvalidated, options Hash and simply generating the resources from that. We don't generally like to do this but, in this case, it's very difficult to keep up with every version in every OS as the SSH daemon versions get updated.

I'd be happy to tackle it once I get my base system up and running.  Maybe have an `$extra_ssh_params` hash that gets merged in.  But first, I want to code a safety-net that validates the config before applying.

**Comment by trevor-vaughan** [comment]
@pillarsdotnet Hmm...I'd love to know what happened to make it fail. The acceptance tests seem to be passing without issue.

Unfortunately, without using a `file` resource, there's really no way to do a pre-validation on a live system. That's where we started and, for SSH in particular, it caused more issues than it solved due to the file complexity and the number of things that people have that randomly poke it.

**Comment by trevor-vaughan** [comment]
Interesting, just got an acceptance test failure: https://gitlab.com/simp/pupmod-simp-ssh/-/jobs/195021019

I can work on getting that cleaned up if you don't want to tackle it. If you'd like to, just let me know and we can help out if necessary.

For more real-time help, you can hit our [Slack channel](https://simp.readthedocs.io/en/master/help/Public_Resources.html#live-chat)

**Comment by pillarsdotnet** [comment]
> Interesting, just got an acceptance test failure: https://gitlab.com/simp/pupmod-simp-ssh/-/jobs/195021019

I suspect it happened because I added a default setting of `'INFO'` for `LogLevel` and your acceptance test applied an additional `LogLevel` of `'VERBOSE'` on top of it.  See lines 175-188 of [`spec/acceptance/suites/default/00_default_spec.rb`](https://github.com/simp/pupmod-simp-ssh/blob/master/spec/acceptance/suites/default/00_default_spec.rb#L175).

I should probably make `$ssh_loglevel` default to `undef` so as to not conflict.

**Comment by pillarsdotnet** [comment]
Looks like the file I need to modify for testing-before-applying is [augeasproviders_ssh/lib/puppet/provider/sshd_config/augeas.rb](https://github.com/hercules-team/augeasproviders_ssh/blob/master/lib/puppet/provider/sshd_config/augeas.rb).

So I'll need to submit a separate PR there.

**Comment by pillarsdotnet** [comment]
Hmm... I got in trouble by specifying an unsupported `MACs` option.  You can check which options are supported by running `ssh -Q mac`.  So I could make a custom-fact and then sanity-check that param before applying.

**Comment by pillarsdotnet** [comment]
Ran into another problem that should probably have an acceptance-test added.

The `usepam` param defaults to `true`.  But if set, it requires the `sssd` pam modules, even if the `sssd` param is set to `false` (the default).

**Comment by trevor-vaughan** [comment]
@pillarsdotnet The `ssh -Q` command doesn't exist on EL6 systems and may not on others. If you decide to go that route (not a bad idea), you'll want to make sure that it's safe and doesn't return anything if the command can't be completed successfully.

**Comment by pillarsdotnet** [comment]
@trevor-vaughan -- Noted; I think I'm done with this PR; will open additional PR's for further improvements.

**Comment by trevor-vaughan** [comment]
:hourglass_flowing_sand: https://gitlab.com/simp/pupmod-simp-ssh/pipelines/56913612

**Comment by trevor-vaughan** [comment]
:hourglass_flowing_sand: https://gitlab.com/simp/pupmod-simp-ssh/pipelines/56926335

**Comment by pillarsdotnet** [comment]
@trevor-vaughan -- Looks like a [pass](https://gitlab.com/simp/pupmod-simp-ssh/pipelines/56926335).

**Pull request merged**
